name: Pull Request Comment

on:
  issue_comment:
    types:
      - created

permissions: write-all

jobs:
  comment:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/answer me')
    outputs:
      branch: ${{ steps.extract_branch.env.BRANCH }}
    steps:
    - name: Extract branch name
      run: |
        echo "BRANCH=$(echo ${{ github.ref_name }} | sed -r 's,/,-,g')" >> $GITHUB_ENV
      id: extract_branch

    - name: check if PR exists
      id: check-pr
      run: |
        PR_EXISTS=$(gh pr list --head ${{ env.branch }} --repo ${{ github.repository }} --state open | wc -l | tr -d ' ')
        if [ $PR_EXISTS -eq 0 ]; then
          echo ::set-output name=exists::false
        else
          echo ::set-output name=exists::true
        fi
      env:
        branch: chore/unknown
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: exec if not exist
      if: steps.check-pr.outputs.exists == 'false'
      run: echo NOT EXISTING

    - name: exec if exists
      if: steps.check-pr.outputs.exists == 'true'
      run: echo EXISTING

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: 'Commenting... on ${{ env.BRANCH }}'
        pr_number: ${{ github.event.issue.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  update-comment:
    needs: comment
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/answer me')
    steps:
    - name: Update comment PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        comment_includes: 'Commenting'
        message: ':rocket: Commented on ${{ needs.comment.outputs.branch }}'
        pr_number: ${{ github.event.issue.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
