name: Release workflow

permissions: write-all

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      type:
        type: choice
        options:
          - Major
          - Minor
          - Patch
        description: 'Release type'
        default: 'Patch'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  change-version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    # Runs a single command using the runners shell
    - name: Major update
      if: ${{ github.event.inputs.type == 'Major' }}
      run: ./upgrade.sh -M
    - name: Minor update
      if: ${{ github.event.inputs.type == 'Minor' }}
      run: ./upgrade.sh -m
    - name: Patch update
      if: ${{ github.event.inputs.type == 'Patch' }}
      run: ./upgrade.sh -p
    - name: Commit change
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add version.json
        git commit -m "chore: release"
        git push origin main

  notify-dependency:
    runs-on: ubuntu-latest
    
    steps:
    - name: request the workflow execution
      env:
        GH_TOKEN: ${{ GITHUB_TOKEN }}
      run: |
        gh workflow run --repo JeanBarriere/gh-action-dependency update_dependency.yml -f dependency_repo=JeanBarriere/gh-action-build-and-release
